# Generated by Django 2.1.15 on 2021-02-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconcept4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ic4_accepted_callover',
            name='Tree_Key',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
