# Generated by Django 2.1.15 on 2021-01-14 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupss',
            fields=[
                ('Group_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Group_Name', models.TextField()),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'Usergroup',
            },
        ),
        migrations.CreateModel(
            name='Ic4_Menus',
            fields=[
                ('menu_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ic4_menus',
            },
        ),
        migrations.CreateModel(
            name='Roless',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Menu_Name', models.CharField(max_length=100)),
                ('Add', models.CharField(max_length=100)),
                ('Edit', models.CharField(max_length=100)),
                ('Delete', models.CharField(max_length=100)),
                ('Group_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Groupss')),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('User_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Group_Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UserRole',
            },
        ),
    ]
